### ISSUE TITLE
Use different folder structure

### ISSUE THREAD

**Issue by chklueter** [mahieakhtar/hyf-homework#1]
Hi @mahieakhtar 

Well done on pushing the files - but the folder structure seems a bit messed up now.
The homework should be pushed to hyf-homework/git/week1

You used the repository hyf-homework-template, which was forked. It makes it a bit messy for us to check on homework.

Please push your homework to hyf-homework/git/week1.  It will make all of our lives easier :) keep up the good work! Almost perfect otherwise :))

**Comment by mahieakhtar** [comment]
my mistake. I have pushed my changes to hyf-homework/git/week1. Please let me know if I have to delete from hyf-homework-template.

**Comment by chklueter** [comment]
It's fine to keep the other folder, the most important is that you have all the homework folders set up in the right structure so it's easy for the mentors to find and check homework directly on github :)
