### ISSUE TITLE
Use parameters as call back.

### ISSUE THREAD

**Issue by Sanahayat** [mahieakhtar/hyf-homework#3]
instead of calling funnyJoke() and badJoke(), you can call logFunnyJoke, logBadJoke here as you already passed them in parameters.
Not that its wrong but You can also use condition if(shouldTellFunnyJoke) as it is same as if (shouldTellFunnyJoke === true).
https://github.com/mahieakhtar/hyf-homework/blob/6e8f6edcac6d3002c6056d905d136a193910291c/javascript/javascript2/week3/warmup/main.js#L90

**Comment by mahieakhtar** [comment]
Thanks, Sanahayat I will update the same

**Comment by mahieakhtar** [comment]
updated
