### ISSUE TITLE
JS2 Week 2 Feedback

### ISSUE THREAD

**Issue by orhantoy** [mahieakhtar/hyf-homework#4]
@mahieakhtar :v:

The feedback is coming a bit late, sorry for that.

## Warmup array exercises / Doubling of number

The idea in this exercise is to do something like this:

```
let numbers = [1, 2, 3, 4]
let newNumbers = numbers.filter( ... ).map( ... )
```

The `...` should be replaced with arrow functions similar to what you have already done.

## Warmup array exercises / Working with movies

- Exercise 1, 2: Nice work here 👍 You didn't have to split the titles by word but this is not a big deal. A simpler approach would be to filter by the `movie.title.length`.
- Exercise 3: ✅ 
- Exercise 4: Nice work here. One smaller issue is that you are actually modifying the objects in `movies` when you set `movie.tag`. You could get around that by copying/duplicating the object.
  https://github.com/mahieakhtar/hyf-homework/blob/18ea77014049a823659381dd7401d12ec443693d/javascript/javascript2/week2/Movies/workingOnMovies.js#L38-L48
- Exercise 5: ✅ 
- Exercise 6: ✅ Next time remember to remove commented code, not a big deal though 👍 
  https://github.com/mahieakhtar/hyf-homework/blob/18ea77014049a823659381dd7401d12ec443693d/javascript/javascript2/week2/Movies/workingOnMovies.js#L60-L67
- Exercise 7: ✅ Nice solution here. The code can be a bit hard to read because the indentation is a bit off.
  https://github.com/mahieakhtar/hyf-homework/blob/18ea77014049a823659381dd7401d12ec443693d/javascript/javascript2/week2/Movies/workingOnMovies.js#L72-L81

## hyfBay - get the okay'est products here - continued

Nice and simple solution here 👍
I would consider improving the empty search, like when the page is initially loaded, to list all products. That way it is easier to an overview and then with search narrow down the results.

**Comment by mahieakhtar** [comment]
I will update the indentation.
Regarding empty search I had an issue earlier but now i got it will load the list and then search can be done
